name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - release

jobs:
  test_and_build:
    name: test and build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 1. set up jdk 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 2. grant execute permission for gradlew
        run: |
          chmod +x gradlew

      - name: 3. test with gradle
        run: |
          notionApiKey=${{ secrets.NOTION_API_KEY }} \
          Blocks_paragraphId=${{ secrets.BLOCKS_PARAGRAPH_ID }} \
          Blocks_todoId=${{ secrets.BLOCKS_TODO_ID }} \
          Blocks_codeId=${{ secrets.BLOCKS_CODE_ID }} \
          Blocks_pageId=${{ secrets.BLOCKS_PAGE_ID }} \
          Databases_databaseId=${{ secrets.DATABASES_DATABASE_ID }} \
          Databases_pageId=${{ secrets.DATABASES_PAGE_ID }} \
          Pages_pageId=${{ secrets.PAGES_PAGE_ID }} \
          ./gradlew test

      - name: 4. build with gradle
        run:
          ./gradlew clean build -x test
